# to make a new key:
# $ mkdir -p ~/.config/sops/age
# $ age-keygen -o ~/.config/sops/age/keys.txt
# nixos:
# $ sudo mkdir -p /var/lib/sops-nix
# $ sudo cp ~/.config/sops/age/keys.txt /var/lib/sops-nix
# $ sudo chown root /var/lib/sops-nix/keys.txt
keys:
  # personal
  - &chinos-mbp23 age1unq0da7h3tc59hme2cyqja9je0v3kg8vtmr3d66y9x95xru7spcsvkhtf0
  - &chinos-twr24 age15k3kews56czw2dczxy07cwstneqalc3r4lcgkm53v6fayxukp9cqkqsfcs
  # servers
  - &chinos-hlb24 age1k5753p7g392d2vkh578pzwrwuhkmg6yphvfrrr94p9u2t287s9dqym6ya2
creation_rules:
  - path_regex: secrets/common.yaml$
    key_groups:
      - age:
          - *chinos-mbp23
          - *chinos-twr24
          - *chinos-hlb24
  - path_regex: secrets/personal.yaml$
    key_groups:
      - age:
          - *chinos-mbp23
          - *chinos-twr24
  - path_regex: secrets/chinos-hlb24.yaml$
    key_groups:
      - age:
          - *chinos-mbp23
          - *chinos-twr24
          - *chinos-hlb24
